### ISSUE TITLE
Tracking feature

### ISSUE THREAD

**Issue by ghost** [mr7495/Sperm_detection_and_tracking#2]
Hi, 
I will use this repo for research, 
But I need also tracking,
You published this  https://github.com/mr7495/Sperm_detection_and_tracking/blob/master/modified_csr-dcf.py
But how I create a csv file for this csr-dcf.py file. 
I need immediately help for tracking.
Please publish for me sperm tracking feature.
Have a nice day,
Regards

**Comment by mr7495** [comment]
Hi
Thank you for reminding this.
You can use 
https://github.com/mr7495/Sperm_detection_and_tracking/blob/master/RetinaNet_testing_on_video(For_counting).ipynb
to generate the CSV file from your video.

**Comment by ghost** [comment]
Thanks for this good work Mr. Mohammad
